# Generated by cpp11: do not edit by hand

rawToUInt8 <- function(x) {
  .Call(`_readNSx_rawToUInt8`, x)
}

rawToInt8 <- function(x) {
  .Call(`_readNSx_rawToInt8`, x)
}

rawToUInt16 <- function(x) {
  .Call(`_readNSx_rawToUInt16`, x)
}

rawToInt16 <- function(x) {
  .Call(`_readNSx_rawToInt16`, x)
}

rawToUInt32 <- function(x) {
  .Call(`_readNSx_rawToUInt32`, x)
}

rawToInt32 <- function(x) {
  .Call(`_readNSx_rawToInt32`, x)
}

rawToInt64 <- function(x) {
  .Call(`_readNSx_rawToInt64`, x)
}

rawToFloat <- function(x) {
  .Call(`_readNSx_rawToFloat`, x)
}

rawToString <- function(x) {
  .Call(`_readNSx_rawToString`, x)
}
