# Generated by cpp11: do not edit by hand

rawToUInt8 <- function(x) {
  .Call(`_readNSx_rawToUInt8`, x)
}

rawToInt8 <- function(x) {
  .Call(`_readNSx_rawToInt8`, x)
}

rawToUInt16 <- function(x) {
  .Call(`_readNSx_rawToUInt16`, x)
}

rawToInt16 <- function(x) {
  .Call(`_readNSx_rawToInt16`, x)
}

rawToUInt32 <- function(x) {
  .Call(`_readNSx_rawToUInt32`, x)
}

rawToInt32 <- function(x) {
  .Call(`_readNSx_rawToInt32`, x)
}

rawToInt64 <- function(x) {
  .Call(`_readNSx_rawToInt64`, x)
}

rawToFloat <- function(x) {
  .Call(`_readNSx_rawToFloat`, x)
}

rawToString <- function(x) {
  .Call(`_readNSx_rawToString`, x)
}

printBCIObject <- function(s) {
  invisible(.Call(`_readNSx_printBCIObject`, s))
}

formatBCIObject <- function(s) {
  .Call(`_readNSx_formatBCIObject`, s)
}

maturalizeBCIObject <- function(s) {
  .Call(`_readNSx_maturalizeBCIObject`, s)
}

bciStrDecode <- function(x, nil) {
  .Call(`_readNSx_bciStrDecode`, x, nil)
}

createBCIObject <- function(cls, config) {
  .Call(`_readNSx_createBCIObject`, cls, config)
}

parseBCIDataRaw <- function(s, x, reset) {
  invisible(.Call(`_readNSx_parseBCIDataRaw`, s, x, reset))
}

parseBCIParamDef <- function(statement) {
  .Call(`_readNSx_parseBCIParamDef`, statement)
}

readNSxDataPacket30 <- function(filePath, nBytes, sampleRate, nChannels, skipBytes, slope, intercept) {
  .Call(`_readNSx_readNSxDataPacket30`, filePath, nBytes, sampleRate, nChannels, skipBytes, slope, intercept)
}

readNSxDataPacket2x <- function(filePath, nBytes, sampleRate, nChannels, skipBytes, slope, intercept) {
  .Call(`_readNSx_readNSxDataPacket2x`, filePath, nBytes, sampleRate, nChannels, skipBytes, slope, intercept)
}
